### ISSUE TITLE
Doesn't work for me.

### ISSUE THREAD

**Issue by glorsh66** [martynassateika/CodeIgniter-phpstorm-plugin#5]
It just doesn't work in my case. It is not showing any autocompletion for my controllers or models.

**Comment by martynassateika** [comment]
Hello @glorsh66, this plug-in is still in quite early stages. I have not tackled controllers or models just yet. So far there's support for translations and views, and I'm about to add initial support for helper files.

**Comment by martynassateika** [comment]
Just merged helper support into master, it should be accessible in a couple of days via the IDE.

I set up an issue for adding model support: https://github.com/martynassateika/CodeIgniter-phpstorm-plugin/issues/6

What did you mean by "autocompletion for controllers" by the way? Trying to remember where controller names are used outside of the controller classes themselves.

**Comment by glorsh66** [comment]
Yeah - you right, I just mistyped. I mean - models and libraries.

**Comment by martynassateika** [comment]
Ahh that makes sense. I set up #7 as well.

Thanks for the input! I'll close this issue for now, subscribe to #6 and #7 if you want to follow progress on those.

0.3.0 should already be accessible via the IDE as of today.
