### ISSUE TITLE
Not getting much code completion at all

### ISSUE THREAD

**Issue by julesbl** [martynassateika/CodeIgniter-phpstorm-plugin#9]
Using
PhpStorm 2019.1
Build #PS-191.6183.95, built on March 27, 2019
Licensed to Julian Blundell
Subscription is active until October 1, 2019
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.10.0-38-generic

Plugin Codeigniter v0.4.0

Trying things like $this->load-> get no suggestions, don't get config at all.

I've tried turning the plugin on and off, disabling and enabling support in the project.

Jules

**Comment by martynassateika** [comment]
Hello Jules,

I have not tackled auto-completion of classes yet so `$this->load` won't list suggestions. That's definitely on my mind, but I wanted to tackle string auto-completion first.

The plugin does not support code completion for CodeIgniter's Config yet. I have just set up https://github.com/martynassateika/CodeIgniter-phpstorm-plugin/issues/10, thanks for the suggestion!

I suppose I should list what actually _is_ supported better in the README file, at the moment you can only see what it does by scanning the changelog.

**Comment by martynassateika** [comment]
Completion and references for config item names are coming in 0.5.0 very soon.

![image](https://user-images.githubusercontent.com/3257241/56766761-1408e180-67a2-11e9-8b49-679db918ab7d.png)
